### ISSUE TITLE
MPICH installation is broken

### ISSUE THREAD

**Issue by diehlpk** [STEllAR-GROUP/rostam-docs#13]
* module load mpich
* export CC=mpicc
* ```
diehlpk@rostam0 build]$ cmake -DPARAVIEW_USE_MPI=ON -DPARAVIEW_BUILD_QT_GUI=OFF -DPARAVIEW_ENABLE_PYTHON=OFF -DCMAKE_INSTALL_PREFIX=/data/octovis/opt/paraview ..
-- The C compiler identification is unknown
-- The CXX compiler identification is unknown
-- Check for working C compiler: /opt/apps/mpich/3.3.2/bin/mpicc
-- Check for working C compiler: /opt/apps/mpich/3.3.2/bin/mpicc -- broken
CMake Error at /opt/apps/cmake/3.16.4/share/cmake-3.16/Modules/CMakeTestCCompiler.cmake:60 (message):
  The C compiler

    "/opt/apps/mpich/3.3.2/bin/mpicc"

  is not able to compile a simple test program.

  It fails with the following output:

    Change Dir: /data/octovis/Compile/ParaView-v5.7.0/build/CMakeFiles/CMakeTmp
    
    Run Build Command(s):/usr/bin/gmake cmTC_9f702/fast && /usr/bin/gmake -f CMakeFiles/cmTC_9f702.dir/build.make CMakeFiles/cmTC_9f702.dir/build
    gmake[1]: Entering directory '/data/octovis/Compile/ParaView-v5.7.0/build/CMakeFiles/CMakeTmp'
    Building C object CMakeFiles/cmTC_9f702.dir/testCCompiler.c.o
    /opt/apps/mpich/3.3.2/bin/mpicc    -o CMakeFiles/cmTC_9f702.dir/testCCompiler.c.o   -c /data/octovis/Compile/ParaView-v5.7.0/build/CMakeFiles/CMakeTmp/testCCompiler.c
    /opt/apps/mpich/3.3.2/bin/mpicc: line 301: /opt/apps/gcc/9.2.0/bin/gcc: No such file or directory
    gmake[1]: *** [CMakeFiles/cmTC_9f702.dir/build.make:66: CMakeFiles/cmTC_9f702.dir/testCCompiler.c.o] Error 127
    gmake[1]: Leaving directory '/data/octovis/Compile/ParaView-v5.7.0/build/CMakeFiles/CMakeTmp'
    gmake: *** [Makefile:121: cmTC_9f702/fast] Error 2
    
    

  

  CMake will not be able to correctly generate this project.
Call Stack (most recent call first):
  CMakeLists.txt:32 (project)
```
* MPICh can not laod the gcc compiler  `/opt/apps/mpich/3.3.2/bin/mpicc: line 301: /opt/apps/gcc/9.2.0/bin/gcc: No such file or directory` 

Just a simple check and there is not such a directory

```
[diehlpk@rostam0 build]$ ls  /opt/apps/gcc/9.2.0/bin/gcc
ls: cannot access '/opt/apps/gcc/9.2.0/bin/gcc': No such file or directory
```

**Comment by akheir** [comment]
Fixed it by recompiling MPICH
