### ISSUE TITLE
Feature: Cuda 9

### ISSUE THREAD

**Issue by diehlpk** [STEllAR-GROUP/rostam-docs#5]

**Comment by akheir** [comment]
Is Cuda 9 necessary? Does it do something that CUDA 10.2 don't?

**Comment by diehlpk** [comment]
Yes, on some systems there is no CUDA 10 available, so we would need to test with CUDA 9 on rostam, before we go to for example Summit.

**Comment by akheir** [comment]
For rhel/centos 8 nvidia didn't release CUDA 9. They only relesed 10.1 and 10.2

Sorry, won't fix.
